### ISSUE TITLE
use https URL instead of git to make easier repros

### ISSUE THREAD

**Issue by weissi** [KosukeOhmura/GRPCSwiftImportChallange#1]
This is unrelated to the bug you're trying to reproduce here but I think it would be easier for others to reproduce if you used

    https://github.com/grpc/grpc-swift.git

as the dependency instead of `git@...` which requires Xcode to have a GitHub.com login

**Comment by kosukeohmura** [comment]
@weissi Thank you for your advice. I've updated the URL.
